version = 1

[merge]
require_automerge_label = false
blacklist_title_regex = "^WIP:.*"
blacklist_labels = ["do-not-merge"]
method = "squash"
delete_branch_on_merge = true
prioritize_ready_to_merge = true

[update]
always = true
require_automerge_label = false
