name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15.x"
      - name: Install formatter
        run: go get -u golang.org/x/tools/cmd/goimports
      - name: Run formatter
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          test -z "$(goimports -l -e .)"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14.x"
      - name: Install linters
        run: |
          mkdir -p bin
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.24.0
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      - name: Run the linters
        run: |
          golangci-lint run \
            --no-config \
            --timeout=30m \
            --disable-all \
            --enable=deadcode  \
            --enable=dupl \
            --enable=errcheck \
            --enable=ineffassign \
            --enable=interfacer \
            --enable=goconst \
            --enable=gocyclo \
            --enable=golint \
            --enable=gosec \
            --enable=maligned \
            --enable=structcheck \
            --enable=unconvert \
            --enable=varcheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14.x"
      - uses: actions/cache@v2.1.3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup the project
        run: go mod download
      - name: Run the unit tests
        run: go test -v -race -cover -coverprofile=coverage.out ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14.x"
      - uses: actions/cache@v2.1.3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup the project
        run: go mod download
      - name: Run Mage
        uses: crazy-max/ghaction-mage@v1
        with:
          version: latest
          args: dist
      - name: Upload artifacts for release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: dist/

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - format
      - lint
      - test
      - build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: binaries
          path: dist/
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1.1.0
      - name: Publish the release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.changelog_reader.outputs.log_entry }}
          files: |
            dist/*
